name: Doover App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  app:
    uses: getdoover/workflows/.github/workflows/app.yml@main
    secrets: inherit
